planner_critic:
  host: localhost
  port: 5001
  url: "http://127.0.0.1:5001/api/planner_critic"
  lmm: "gemini-2.0-flash-exp"
  lmm_critic: "gemini-2.0-flash-exp"
gui_parser:
  host: localhost
  port: 5002
  url: "http://127.0.0.1:5002/api/gui_parser"
step_check:
  host: localhost
  port: 5003
  url: "http://127.0.0.1:5003/api/step_check"
  lmm: "gemini-2.0-flash-exp"
actor:
  host: localhost
  port: 5004
  url: "http://127.0.0.1:5004/api/actor"
  lmm: "gemini-2.0-flash-exp"
actorcritic:
  host: localhost
  port: 5005
  url: "http://127.0.0.1:5005/api/actorcritic"
  lmm: "gemini-2.0-flash-exp"
  critic_lmm: "gemini-2.0-flash-exp"
os_agent_settings:
  cache_dir: "./backend_cache"

# candidate models used in our GUI-Thinker
# claude-3-7-sonnet-20250219
# gpt-4o-2024-08-06
# gemini-2.0-flash-exp
# claude-3-5-sonnet-20241022
